export const COLOR_MODE_TOKENS = {
  dark: {
    colorScheme: 'dark',
    appBg: '#080b14',
    appBgAlt: '#101626',
    appBgSoft: '#141b2d',
    surface: 'rgba(17, 24, 39, 0.84)',
    surfaceElevated: 'rgba(27, 36, 58, 0.92)',
    surfaceHover: 'rgba(39, 50, 77, 0.9)',
    surfaceSolid: '#151d30',
    text: '#f7f9ff',
    textSecondary: '#c8d2e5',
    textMuted: '#8f9bb1',
    textDisabled: 'rgba(200, 210, 229, 0.5)',
    border: 'rgba(148, 163, 184, 0.18)',
    borderStrong: 'rgba(203, 213, 225, 0.3)',
    overlaySoft: 'rgba(2, 6, 23, 0.36)',
    overlayStrong: 'rgba(2, 6, 23, 0.62)',
    controlSolid: 'rgba(20, 27, 45, 0.9)',
    success: '#4ade80',
    warning: '#fbbf24',
    danger: '#fb7185',
    info: '#60a5fa',
    shadowSm: '0 8px 22px rgba(0, 0, 0, 0.28)',
    shadowMd: '0 18px 44px rgba(0, 0, 0, 0.36)',
    shadowLg: '0 30px 80px rgba(0, 0, 0, 0.48)',
  },
  light: {
    colorScheme: 'light',
    appBg: '#f5f7fb',
    appBgAlt: '#edf2f8',
    appBgSoft: '#e8eef6',
    surface: 'rgba(255, 255, 255, 0.82)',
    surfaceElevated: 'rgba(255, 255, 255, 0.95)',
    surfaceHover: 'rgba(237, 242, 248, 0.96)',
    surfaceSolid: '#ffffff',
    text: '#101828',
    textSecondary: '#344054',
    textMuted: '#667085',
    textDisabled: 'rgba(102, 112, 133, 0.58)',
    border: 'rgba(16, 24, 40, 0.12)',
    borderStrong: 'rgba(16, 24, 40, 0.22)',
    overlaySoft: 'rgba(15, 23, 42, 0.08)',
    overlayStrong: 'rgba(15, 23, 42, 0.18)',
    controlSolid: 'rgba(255, 255, 255, 0.9)',
    success: '#15803d',
    warning: '#b45309',
    danger: '#be123c',
    info: '#2563eb',
    shadowSm: '0 8px 22px rgba(15, 23, 42, 0.08)',
    shadowMd: '0 18px 44px rgba(15, 23, 42, 0.12)',
    shadowLg: '0 30px 80px rgba(15, 23, 42, 0.16)',
  },
};

export const STATUS_COLORS = {
  watched: '#e11d48',
  planned: '#3b82f6',
  watching: '#8b5cf6',
  paused: '#f59e0b',
  dropped: '#ef4444',
};

export const buildColorModeVars = (darkMode) => {
  const c = COLOR_MODE_TOKENS[darkMode ? 'dark' : 'light'];

  return {
    '--app-bg-base': c.appBg,
    '--bg-base': c.appBg,
    '--bg-elevated': c.surfaceElevated,
    '--bg-card': c.surface,
    '--bg-glass': c.surface,
    '--app-bg-alt': c.appBgAlt,
    '--app-bg-soft': c.appBgSoft,
    '--theme-bg': c.appBg,
    '--theme-bg-alt': c.appBgAlt,
    '--theme-bg-secondary': c.appBgAlt,
    '--theme-bg-tertiary': c.appBgSoft,
    '--theme-surface': c.surface,
    '--theme-surface-elevated': c.surfaceElevated,
    '--theme-surface-hover': c.surfaceHover,
    '--theme-surface-solid': c.surfaceSolid,
    '--surface-1': c.surface,
    '--surface-2': c.surfaceElevated,
    '--surface-3': c.surfaceHover,
    '--theme-text': c.text,
    '--theme-text-primary': c.text,
    '--theme-text-secondary': c.textSecondary,
    '--theme-text-muted': c.textMuted,
    '--theme-text-disabled': c.textDisabled,
    '--text-primary': c.text,
    '--text-secondary': c.textSecondary,
    '--text-muted': c.textMuted,
    '--text-disabled': c.textDisabled,
    '--theme-border': c.border,
    '--theme-border-strong': c.borderStrong,
    '--border': c.border,
    '--border-hover': c.borderStrong,
    '--border-active': c.borderStrong,
    '--theme-success': c.success,
    '--theme-warning': c.warning,
    '--theme-danger': c.danger,
    '--theme-info': c.info,
    '--status-watched': STATUS_COLORS.watched,
    '--status-planned': STATUS_COLORS.planned,
    '--status-watching': STATUS_COLORS.watching,
    '--status-paused': STATUS_COLORS.paused,
    '--status-dropped': STATUS_COLORS.dropped,
    '--theme-success-soft': `color-mix(in srgb, ${c.success} 14%, transparent)`,
    '--theme-warning-soft': `color-mix(in srgb, ${c.warning} 16%, transparent)`,
    '--theme-danger-soft': `color-mix(in srgb, ${c.danger} 14%, transparent)`,
    '--overlay-soft': c.overlaySoft,
    '--overlay-dark': c.overlayStrong,
    '--overlay-strong': c.overlayStrong,
    '--control-solid-bg': c.controlSolid,
    '--shadow-sm': c.shadowSm,
    '--shadow-md': c.shadowMd,
    '--shadow-lg': c.shadowLg,
    '--elevation-surface-1': c.shadowSm,
    '--elevation-surface-2': c.shadowMd,
    '--elevation-surface-3': c.shadowLg,
  };
};
