export const MOBILE_TABS = ["assets", "avatar", "text"];

export const UI_PARITY_TOKENS = {
  spacing: { xs: '6px', sm: '10px', md: '14px', lg: '18px', xl: '24px' },
  typography: {
    display: 'clamp(2.4rem, 6vw, 4.75rem)',
    h1: 'clamp(1.7rem, 4vw, 2.5rem)',
    h2: 'clamp(1.25rem, 3vw, 1.75rem)',
    body: '1rem',
    caption: '0.78rem',
  },
  radius: { sm: '10px', md: '12px', lg: '16px' },
  motion: { fast: '150ms', base: '200ms', slow: '240ms' },
  contrastTargets: { normalText: '4.5:1', largeText: '3:1', nonTextUI: '3:1' },
};

export const COLOR_MODE_TOKENS = {
  dark: {
    bg: '#070a12',
    bgSecondary: '#0d1323',
    bgTertiary: '#121a2d',
    surface: 'rgba(17, 24, 39, 0.84)',
    surfaceElevated: 'rgba(25, 34, 52, 0.92)',
    surfaceStrong: 'rgba(32, 43, 64, 0.96)',
    text: '#f7fbff',
    textSecondary: '#c4cede',
    textMuted: '#95a3b8',
    textDisabled: 'rgba(149, 163, 184, 0.58)',
    border: 'rgba(148, 163, 184, 0.18)',
    borderHover: 'rgba(148, 163, 184, 0.3)',
    borderActive: 'rgba(148, 163, 184, 0.42)',
    overlaySoft: 'rgba(3, 7, 18, 0.34)',
    overlayDark: 'rgba(3, 7, 18, 0.54)',
    overlayStrong: 'rgba(3, 7, 18, 0.68)',
    shadowSm: '0 8px 22px rgba(0, 0, 0, 0.24)',
    shadowMd: '0 18px 42px rgba(0, 0, 0, 0.34)',
    shadowLg: '0 28px 70px rgba(0, 0, 0, 0.46)',
    appBase: '#070a12',
    vignette: 'rgba(29, 78, 216, 0.18)',
    panelMix: 'rgba(15, 23, 42, 0.72)',
    inputBg: 'rgba(15, 23, 42, 0.62)',
    success: '#3ddc84',
    warning: '#f6c453',
    danger: '#ff6b7a',
  },
  light: {
    bg: '#f6f8fc',
    bgSecondary: '#eef3fa',
    bgTertiary: '#e6edf7',
    surface: 'rgba(255, 255, 255, 0.82)',
    surfaceElevated: 'rgba(255, 255, 255, 0.94)',
    surfaceStrong: 'rgba(255, 255, 255, 0.98)',
    text: '#101828',
    textSecondary: '#344054',
    textMuted: '#667085',
    textDisabled: 'rgba(102, 112, 133, 0.56)',
    border: 'rgba(15, 23, 42, 0.12)',
    borderHover: 'rgba(15, 23, 42, 0.2)',
    borderActive: 'rgba(15, 23, 42, 0.28)',
    overlaySoft: 'rgba(15, 23, 42, 0.07)',
    overlayDark: 'rgba(15, 23, 42, 0.13)',
    overlayStrong: 'rgba(15, 23, 42, 0.2)',
    shadowSm: '0 8px 20px rgba(16, 24, 40, 0.08)',
    shadowMd: '0 18px 38px rgba(16, 24, 40, 0.12)',
    shadowLg: '0 28px 62px rgba(16, 24, 40, 0.16)',
    appBase: '#f6f8fc',
    vignette: 'rgba(59, 130, 246, 0.12)',
    panelMix: 'rgba(255, 255, 255, 0.72)',
    inputBg: 'rgba(255, 255, 255, 0.78)',
    success: '#178c4f',
    warning: '#b7791f',
    danger: '#c8324b',
  },
};

export const buildSemanticThemeVars = (darkMode) => {
  const mode = darkMode ? 'dark' : 'light';
  const c = COLOR_MODE_TOKENS[mode];

  return {
    '--theme-bg': c.bg,
    '--theme-bg-secondary': c.bgSecondary,
    '--theme-bg-tertiary': c.bgTertiary,
    '--theme-bg-alt': c.bgSecondary,
    '--theme-surface': c.surface,
    '--theme-surface-elevated': c.surfaceElevated,
    '--theme-surface-strong': c.surfaceStrong,
    '--theme-surface-hover': `color-mix(in srgb, ${c.surfaceElevated} 86%, var(--theme-accent))`,
    '--theme-input-bg': c.inputBg,
    '--theme-panel-mix': c.panelMix,
    '--theme-border': c.border,
    '--theme-border-hover': c.borderHover,
    '--theme-border-active': c.borderActive,
    '--theme-text': c.text,
    '--theme-text-primary': c.text,
    '--theme-text-secondary': c.textSecondary,
    '--theme-text-muted': c.textMuted,
    '--theme-text-disabled': c.textDisabled,
    '--theme-success': c.success,
    '--theme-warning': c.warning,
    '--theme-danger': c.danger,
    '--theme-success-soft': `color-mix(in srgb, ${c.success} ${darkMode ? 18 : 12}%, transparent)`,
    '--theme-warning-soft': `color-mix(in srgb, ${c.warning} ${darkMode ? 18 : 12}%, transparent)`,
    '--theme-danger-soft': `color-mix(in srgb, ${c.danger} ${darkMode ? 18 : 12}%, transparent)`,
    '--overlay-soft': c.overlaySoft,
    '--overlay-dark': c.overlayDark,
    '--overlay-strong': c.overlayStrong,
    '--shadow-sm': c.shadowSm,
    '--shadow-md': c.shadowMd,
    '--shadow-lg': c.shadowLg,
    '--app-bg-base': c.appBase,
    '--app-bg-vignette': c.vignette,
    '--chip-bg': `color-mix(in srgb, ${c.surfaceElevated} 72%, transparent)`,
    '--chip-bg-hover': `color-mix(in srgb, ${c.surfaceStrong} 84%, var(--theme-accent) 8%)`,
    '--chip-border': c.border,
    '--chip-border-active': c.borderHover,
    '--chip-text': c.textSecondary,
    '--chip-text-active': c.text,
  };
};

export const UI_TOKENS = {
  panel: { level1: 'var(--ui-panel-1)', level2: 'var(--ui-panel-2)' },
  border: { soft: 'var(--ui-border-soft)', strong: 'var(--ui-border-strong)' },
  shadow: { level1: 'var(--ui-shadow-1)', level2: 'var(--ui-shadow-2)' },
  spacing: {
    xs: 'var(--ui-space-1)', sm: 'var(--ui-space-2)', md: 'var(--ui-space-3)', lg: 'var(--ui-space-4)',
  },
  radius: { sm: 'var(--ui-radius-sm)', md: 'var(--ui-radius-md)', lg: 'var(--ui-radius-lg)' },
};
